### ISSUE TITLE
Cache vagrant boxes in github actions

### ISSUE THREAD

**Issue by apatard** [pycontribs/python-vagrant#128]
Seeing log failures like:
```
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
The requested URL returned error: 429
```
(https://github.com/pycontribs/python-vagrant/runs/7184689242?check_suite_focus=true#step:9:130)

I'm wondering if setting a cache would avoid this ?

If so, what would be the correct key ? something like:
```
${{ runner.os }}-${{ matrix.tox_env }}-vagrantbox-${{ hashFiles('tests/tools/create_dummy_box.sh', 'tests/test_vagrant*py', '**/Vagrantfile', 'tests/vagrantfiles/*Vagrantfile') }}
```

**Comment by konstruktoid** [comment]
Sounds like a great idea, but will that actually cache `.vagrant/machines` where the VMs are stored?

**Comment by konstruktoid** [comment]
ah yes, i actually meant the boxes, not the vms :/ 
`path:  ~/.vagrant.d/boxes` was the part i was missing from the first code line above
