### ISSUE TITLE
support to get stderr for failed vagrant commands

### ISSUE THREAD

**Issue by miqsoft** [pycontribs/python-vagrant#139]
In some cases it is needed/helpful to get the stderr after you run vagrant up (or another vagrant command) and it failed.

As far as I can see this is not implemented in the source code so far. Would be amazing to have this possibility within python-vagrant.

**Comment by apatard** [comment]
Not sure what's exactly you meant, but it's possible to get stderr content, via a context manager. See https://github.com/pycontribs/python-vagrant/blob/main/README.md#logging-the-stdout-or-stderr-of-the-vagrant-subprocess.

**Comment by miqsoft** [comment]
Thanks for the fast response. This is what I meant. Sorry for not reading the documentation properly
