### ISSUE TITLE
not displaying output when asked to

### ISSUE THREAD

**Issue by SashaOv** [pycontribs/python-vagrant#48]
This is the code to demonstrate the problem:

```
  import vagrant

  # This is to demonstrate the problem that the package is not displaying output when asked to
  #
  #     > python vagrant_eats_output.py
  #     Connection to 127.0.0.1 closed.

  v= vagrant.Vagrant(quiet_stderr=False, quiet_stdout=False, err_cm=vagrant.stderr_cm, out_cm=vagrant.stdout_cm)
  v._run_vagrant_command(["ssh", "-c", "echo Hello"])     
```

**Comment by todddeluca** [comment]
Since `_run_vagrant_command` internally uses `subprocess.check_output` to capture the output, it ignores `out_cm`.  Use `_call_vagrant_command` instead, if using `out_cm`.

See https://docs.python.org/2/library/subprocess.html#subprocess.check_output for more details.
