### ISSUE TITLE
Need option to save cached configuration to disk

### ISSUE THREAD

**Issue by bryanwb** [pycontribs/python-vagrant#52]
Hello Todd! I am writing a soon to be open-sourced tool called labrat that uses your wonderful library. I have implemented a mechanism to cache the vagrant instance's configuration to disk. I basically serialize `vagrant.Vagrant._cache_conf` to json. This feature would better live in python-vagrant imo. Would you be open to a PR for it?

**Comment by todddeluca** [comment]
Hi Bryan,

The current scope of python-vagrant is to act as a *thin* python API around the vagrant CLI.  I hesitate to expand that scope.  I would be open to creating a method or public member variable for `_cache_conf`.  

That being said, I do not use python-vagrant in my own work anymore and only maintain it for the sake of its community of users.  I would be open to adding maintainers to the project and letting them decide the scope and direction of python-vagrant.  Do you have any interest in being a maintainer?

Regards,
Todd

**Comment by bryanwb** [comment]
Hi @todddeluca I might be interested in being a maintainer but my first priority is to open-source the tool i have been working on, known as labrat. Labrat is makes it easy to spin up "labs" in which you install your application using py.test fixtures and executes integration tests against your application written in py.test. Thanks for thinking of me. I'll try to come back to this

**Comment by kodelint** [comment]
@todddeluca First of all thank you very much for writing this wrapper for `vagrant`. It helped me a lot to manage my vagrant instances programmatically.  I really love this and I am using this in my open source project. I would be more than happy to maintain this repo.

**Comment by bryanwb** [comment]
@todddeluca circumstances have changed and i would be happy to be a maintainer of python-vagrant. Sorry for the very, very belated answer :)

**Comment by ssbarnea** [comment]
Closing but if @bryanwb is still interested, we can reopen the subject. I kinda find the subject appealing.
