### ISSUE TITLE
python-vagrant not working in Git Bash

### ISSUE THREAD

**Issue by AdamBalali** [pycontribs/python-vagrant#59]
In the latest Git Bash (Windows), python-vagrant stopped working.
The only issue I've found is: 
for example, if I want to run: vagrant status
I'm getting the return code: 1 with the following error:
```
stdout is not a tty
Traceback (most recent call last):
  File "C:\Python27\Scripts\vagrastack-script.py", line 11, in <module>
    load_entry_point('VagraStack==0.2.16', 'console_scripts', 'vagrastack')()
  File "c:\python27\lib\site-packages\vagrastack\vagrastack.py", line 213, in main
    VagraStack()
  File "c:\python27\lib\site-packages\vagrastack\vagrastack.py", line 71, in __init__
    getattr(self, args.command)()
  File "c:\python27\lib\site-packages\vagrastack\vagrastack.py", line 131, in status
    self.vagrant.vagrant_status(args.machine)
  File "c:\python27\lib\site-packages\vagrastack\Vagrant.py", line 48, in vagrant_status
    for machine in self.vagrant_cli.status():
  File "c:\python27\lib\site-packages\vagrant\__init__.py", line 494, in status
    output = self._run_vagrant_command(['status', '--machine-readable', vm_name])
  File "c:\python27\lib\site-packages\vagrant\__init__.py", line 979, in _run_vagrant_command
    env=self.env, stderr=err_fh))
  File "c:\python27\lib\subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['c:\\hashicorp\\vagrant\\bin\\vagrant.exe', 'status', '--machine-readable']' returned non-zero exit status 1
```
If I'm running it using Git CMD, or CMD, everything works fine.
I haven't found a solution for that, would really appreciate if you have time to fix it.

**Comment by todddeluca** [comment]
Googling 'stdout is not a tty git bash' turns up hits that might be relevant to this behavior.  However, not having access to a Windows machine, I can't reproduce this error.  When initializing the `Vagrant` object, did you set `err_cm` to something other than the default `none_cm`?

**Comment by AdamBalali** [comment]
At first I haven't changed err_cm to anything, just used the default ones. To see the `stdout is not a tty` error, I had to initialize Vagrant object with: `quiet_stderr=False, quiet_stdout=False, err_cm=vagrant.stderr_cm, out_cm=vagrant.stdout_cm`.

**Comment by GhostofGoes** [comment]
This may be related to your issue: IIRC, there are issues with running python from the terminal if you are using MSYS2 for the terminal in Git for Windows. Check the known issues in the release notes. (Can't find these online, but they're included in the download)

**Comment by todddeluca** [comment]
I'm not able to debug Windows issues.  I'm open to a PR if someone wants to
submit one.

**Comment by Wyko** [comment]
That's unfortunate. I'm coding on Windows and could definitely use this functionality.
