### ISSUE TITLE
box_list() failing

### ISSUE THREAD

**Issue by uniqx** [pycontribs/python-vagrant#66]
Hi, I think I hit a bug in `box_list()`

my python-vagrant version is:

    % pip3 freeze | grep vagrant
    python-vagrant==0.5.15

my vagrant version is:

    % vagrant --version
    Vagrant 1.9.1

Here is the stackstrace:

    >>> import vagrant
    >>> v = vagrant.Vagrant(root="buildserver")
    >>> v.box_list()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/uniq/.local/lib/python3.5/site-packages/vagrant/__init__.py", line 688, in box_list
        return self._parse_box_list(output)
      File "/home/uniq/.local/lib/python3.5/site-packages/vagrant/__init__.py", line 774, in _parse_box_list
        for timestamp, target, kind, data in self._parse_machine_readable_output(output):
    ValueError: too many values to unpack (expected 4)

Here is the output of `vagrant box list --machine-readable` my machine:

    % vagrant box list --machine-readable
    1536671612,,ui,info,debian/jessie64                 (virtualbox%!(VAGRANT_COMMA) 8.10.0)
    1536671612,,box-name,debian/jessie64
    1536671612,,box-provider,virtualbox
    1536671612,,box-version,8.10.0
    1536671612,,ui,info,debian/jessie64                 (libvirt%!(VAGRANT_COMMA) 8.7.0)
    1536671612,,box-name,debian/jessie64
    1536671612,,box-provider,libvirt
    1536671612,,box-version,8.7.0
    1536671612,,ui,info,debian/stretch64                (libvirt%!(VAGRANT_COMMA) 9.0.0-rc3)
    1536671612,,box-name,debian/stretch64
    1536671612,,box-provider,libvirt
    1536671612,,box-version,9.0.0-rc3
    1536671612,,ui,info,debian/stretch64                (libvirt%!(VAGRANT_COMMA) 9.1.0)
    1536671612,,box-name,debian/stretch64
    1536671612,,box-provider,libvirt
    1536671612,,box-version,9.1.0
    1536671612,,ui,info,debian/stretch64                (virtualbox%!(VAGRANT_COMMA) 9.2.0)
    1536671612,,box-name,debian/stretch64
    1536671612,,box-provider,virtualbox
    1536671612,,box-version,9.2.0
    1536671612,,ui,info,fdroid-stretch64                (libvirt%!(VAGRANT_COMMA) 0)
    1536671612,,box-name,fdroid-stretch64
    1536671612,,box-provider,libvirt
    1536671612,,box-version,0
    1536671612,,ui,info,generic/ubuntu1810              (libvirt%!(VAGRANT_COMMA) 1.8.14)
    1536671612,,box-name,generic/ubuntu1810
    1536671612,,box-provider,libvirt
    1536671612,,box-version,1.8.14
    1536671612,,box-info,Author,Ladar Levison
    1536671612,,box-info,Website,https://roboxes.org/
    1536671612,,box-info,Repository,https://github.com/lavabit/robox/
    1536671612,,box-info,Description,Basic virtual machine images%!(VAGRANT_COMMA) for a variety of operating systems/hypervisors%!(VAGRANT_COMMA) and ready to serve as base bxoes.
    1536671612,,ui,info,ninoles/debian-gitlab-ci-runner (virtualbox%!(VAGRANT_COMMA) 1.0.0)
    1536671612,,box-name,ninoles/debian-gitlab-ci-runner
    1536671612,,box-provider,virtualbox
    1536671612,,box-version,1.0.0

don't think that's really related but here's also my list of vagrant plugins:

    % vagrant plugin list
    vagrant-disksize (0.1.2)
    vagrant-libvirt (0.0.37, system)
    vagrant-mutate (1.2.0, system)
    vagrant-scp (0.5.7)

**Comment by mormegil-cz** [comment]
Yeah, I hit the same bug now; the problem seems to be the `box-info` entries, containing a comma-separated attribute-value pairs without using `%!(VAGRANT_COMMA)`.

**Comment by apatard** [comment]
Hi.
I believe that this issue has been fixed by https://github.com/pycontribs/python-vagrant/commit/04a45ae457729d12c6c1c885a8e56b27b368f7d7.

I'm closing this bug but if it's not, please reopen a bug.
